services:
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=recorder
      - POSTGRES_USER=recorder
      - POSTGRES_PASSWORD=baguvix123FFF
    command: -p 5433
    ports:
      - "5433:5432"
  web:
    build: .
    command: "gunicorn --bind 0.0.0.0:8000 district_map_backend.wsgi:application"
#    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  postgres_data: