# Generated by Django 5.0.6 on 2024-08-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geometryobject',
            options={'verbose_name': 'Гео обьекты', 'verbose_name_plural': 'Гео обьекты'},
        ),
        migrations.AlterModelOptions(
            name='geometryobjectcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
