# Generated by Django 5.0.6 on 2024-08-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0002_alter_geometryobject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geometryobjectcategory',
            options={'verbose_name': '    Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
