# Generated by Django 5.0.6 on 2025-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0005_alter_regioninfo_category_alter_regioninfo_region'),
        ('geometry', '0004_alter_geometryobjectcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometryobject',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='geometryobject',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='geometryobject',
            index=models.Index(fields=['latitude'], name='geometry_ge_latitud_831960_idx'),
        ),
        migrations.AddIndex(
            model_name='geometryobject',
            index=models.Index(fields=['longitude'], name='geometry_ge_longitu_64feca_idx'),
        ),
    ]
