# Generated by Django 5.0.6 on 2024-08-20 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_geographicregion_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicregion',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='dwelling_count',
            field=models.IntegerField(default=0, verbose_name='Тургын уй'),
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='population_count',
            field=models.IntegerField(default=0, verbose_name='Адам саны'),
        ),
        migrations.CreateModel(
            name='RegionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('information_keys', models.JSONField(default=[])),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='district.geographicregion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
