# Generated by Django 5.0.6 on 2024-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_district_latitude_district_longitude_district_zoom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='village',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='village',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='villagedistrict',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='villagedistrict',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
