# Generated by Django 5.0.6 on 2024-08-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_alter_geographicregion_options_and_more'),
        ('geometry', '0003_alter_geometryobjectcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioninfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='geometry.geometryobjectcategory'),
        ),
    ]
