# Generated by Django 5.0.6 on 2024-08-22 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0004_regioninfo_category'),
        ('geometry', '0003_alter_geometryobjectcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioninfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='geometry.geometryobjectcategory'),
        ),
        migrations.AlterField(
            model_name='regioninfo',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='district.geographicregion'),
        ),
    ]
